# Generated by Django 4.1.3 on 2022-12-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_alter_todo_datecomplited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
